version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    runtime-versions:
      python: 3.10.18
    commands:
      - echo "Installing CD dependencies"
      - pip install --upgrade pip
      - pip install -r pipelines/requirements.txt

  pre_build:
    commands:
      - echo "CD Stage-1: Pipeline upsert"
      - python --version
      - ls -la

  build:
    commands:
      - echo "Upserting SageMaker training pipeline"
      - python pipelines/training_pipeline.py --execute

  post_build:
    commands:
      - echo "Pipeline definition updated successfully"
